CREATE TABLE IF NOT EXISTS `keywords` (
	`id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`keyword` VARCHAR(255) NOT NULL UNIQUE,
	`lr` VARCHAR(10) NOT NULL DEFAULT 'lang_en',
	`cr` VARCHAR(10) NOT NULL DEFAULT 'countryUS',
	INDEX `lrs`(`lr`),
	INDEX `crs`(`cr`),
	FOREIGN KEY(`lr`) REFERENCES `google_languages`(`lr`) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(`cr`) REFERENCES `google_countries`(`cr`) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `domains` (
	`id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`host` VARCHAR(255) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `proxies` (
	`id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`host` VARCHAR(255) NOT NULL UNIQUE,
	`username` VARCHAR(255) DEFAULT NULL,
	`password` VARCHAR(255) DEFAULT NULL,
	`port` INT DEFAULT 80,
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


CREATE TABLE IF NOT EXISTS `google_search_results` (
	`year` INT(4) NOT NULL DEFAULT YEAR(CURRENT_TIMESTAMP),
	`month` INT(2) NOT NULL DEFAULT MONTH(CURRENT_TIMESTAMP),
	`keyword_id` INT NOT NULL,
	-- PRIMARY KEY (`date`, `keyword_id`),
	-- INDEX `keyword`(`keyword_id`),
	-- FOREIGN KEY(`keyword_id`) REFERENCES `keywords`(`keyword_id`) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
