DROP TABLE IF EXISTS `google_languages`;
DROP TABLE IF EXISTS `google_countries`;

CREATE TABLE IF NOT EXISTS `google_languages` (
	`lr` VARCHAR(10) NOT NULL PRIMARY KEY,
	`label` VARCHAR(255) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `google_countries` (
	`cr` VARCHAR(10) NOT NULL PRIMARY KEY,
	`label` VARCHAR(255) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `google_languages` VALUES
	('lang_af', 'Afrikaans'),
	('lang_ar', 'Arabic'),
	('lang_hy', 'Armenian'),
	('lang_be', 'Belarusian'),
	('lang_bg', 'Bulgarian'),
	('lang_ca', 'Catalan'),
	('lang_zh-CN', 'Chinese (Simplified)'),
	('lang_zh-TW', 'Chinese (Traditional)'),
	('lang_hr', 'Croatian'),
	('lang_cs', 'Czech'),
	('lang_da', 'Danish'),
	('lang_nl', 'Dutch'),
	('lang_en', 'English'),
	('lang_eo', 'Esperanto'),
	('lang_et', 'Estonian'),
	('lang_tl', 'Filipino'),
	('lang_fi', 'Finnish'),
	('lang_fr', 'French'),
	('lang_de', 'German'),
	('lang_el', 'Greek'),
	('lang_iw', 'Hebrew'),
	('lang_hi', 'Hindi'),
	('lang_hu', 'Hungarian'),
	('lang_is', 'Icelandic'),
	('lang_id', 'Indonesian'),
	('lang_it', 'Italian'),
	('lang_ja', 'Japanese'),
	('lang_ko', 'Korean'),
	('lang_lv', 'Latvian'),
	('lang_lt', 'Lithuanian'),
	('lang_no', 'Norwegian'),
	('lang_fa', 'Persian'),
	('lang_pl', 'Polish'),
	('lang_pt', 'Portuguese'),
	('lang_ro', 'Romanian'),
	('lang_ru', 'Russian'),
	('lang_sr', 'Serbian'),
	('lang_sk', 'Slovak'),
	('lang_sl', 'Slovenian'),
	('lang_es', 'Spanish'),
	('lang_sw', 'Swahili'),
	('lang_sv', 'Swedish'),
	('lang_th', 'Thai'),
	('lang_tr', 'Turkish'),
	('lang_uk', 'Ukrainian'),
	('lang_vi', 'Vietnamese');

INSERT INTO `google_countries` VALUES
	('countryAF', 'Afghanistan'),
	('countryAL', 'Albania'),
	('countryDZ', 'Algeria'),
	('countryAS', 'American Samoa'),
	('countryAD', 'Andorra'),
	('countryAO', 'Angola'),
	('countryAI', 'Anguilla'),
	('countryAQ', 'Antarctica'),
	('countryAG', 'Antigua and Barbuda'),
	('countryAR', 'Argentina'),
	('countryAM', 'Armenia'),
	('countryAW', 'Aruba'),
	('countryAU', 'Australia'),
	('countryAT', 'Austria'),
	('countryAZ', 'Azerbaijan'),
	('countryBS', 'Bahamas'),
	('countryBH', 'Bahrain'),
	('countryBD', 'Bangladesh'),
	('countryBB', 'Barbados'),
	('countryBY', 'Belarus'),
	('countryBE', 'Belgium'),
	('countryBZ', 'Belize'),
	('countryBJ', 'Benin'),
	('countryBM', 'Bermuda'),
	('countryBT', 'Bhutan'),
	('countryBO', 'Bolivia'),
	('countryBA', 'Bosnia and Herzegovina'),
	('countryBW', 'Botswana'),
	('countryBV', 'Bouvet Island'),
	('countryBR', 'Brazil'),
	('countryIO', 'British Indian Ocean Territory'),
	('countryVG', 'British Virgin Islands'),
	('countryBN', 'Brunei'),
	('countryBG', 'Bulgaria'),
	('countryBF', 'Burkina Faso'),
	('countryBI', 'Burundi'),
	('countryKH', 'Cambodia'),
	('countryCM', 'Cameroon'),
	('countryCA', 'Canada'),
	('countryCV', 'Cape Verde'),
	('countryKY', 'Cayman Islands'),
	('countryCF', 'Central African Republic'),
	('countryTD', 'Chad'),
	('countryCL', 'Chile'),
	('countryCN', 'China'),
	('countryCX', 'Christmas Island'),
	('countryCC', 'Cocos [Keeling] Islands'),
	('countryCO', 'Colombia'),
	('countryKM', 'Comoros'),
	('countryCD', 'Congo [DRC]'),
	('countryCG', 'Congo [Republic]'),
	('countryCK', 'Cook Islands'),
	('countryCR', 'Costa Rica'),
	('countryCI', 'Cote d’Ivoire'),
	('countryHR', 'Croatia'),
	('countryCU', 'Cuba'),
	('countryCY', 'Cyprus'),
	('countryCZ', 'Czech Republic'),
	('countryDK', 'Denmark'),
	('countryDJ', 'Djibouti'),
	('countryDM', 'Dominica'),
	('countryDO', 'Dominican Republic'),
	('countryEC', 'Ecuador'),
	('countryEG', 'Egypt'),
	('countrySV', 'El Salvador'),
	('countryGQ', 'Equatorial Guinea'),
	('countryER', 'Eritrea'),
	('countryEE', 'Estonia'),
	('countryET', 'Ethiopia'),
	('countryFK', 'Falkland Islands [Islas Malvinas]'),
	('countryFO', 'Faroe Islands'),
	('countryFJ', 'Fiji'),
	('countryFI', 'Finland'),
	('countryFR', 'France'),
	('countryGF', 'French Guiana'),
	('countryPF', 'French Polynesia'),
	('countryTF', 'French Southern Territories'),
	('countryGA', 'Gabon'),
	('countryGM', 'Gambia'),
	('countryGE', 'Georgia'),
	('countryDE', 'Germany'),
	('countryGH', 'Ghana'),
	('countryGI', 'Gibraltar'),
	('countryGR', 'Greece'),
	('countryGL', 'Greenland'),
	('countryGD', 'Grenada'),
	('countryGP', 'Guadeloupe'),
	('countryGU', 'Guam'),
	('countryGT', 'Guatemala'),
	('countryGN', 'Guinea'),
	('countryGW', 'Guinea-Bissau'),
	('countryGY', 'Guyana'),
	('countryHT', 'Haiti'),
	('countryHM', 'Heard Island and McDonald Islands'),
	('countryHN', 'Honduras'),
	('countryHK', 'Hong Kong'),
	('countryHU', 'Hungary'),
	('countryIS', 'Iceland'),
	('countryIN', 'India'),
	('countryID', 'Indonesia'),
	('countryIR', 'Iran'),
	('countryIQ', 'Iraq'),
	('countryIE', 'Ireland'),
	('countryIL', 'Israel'),
	('countryIT', 'Italy'),
	('countryJM', 'Jamaica'),
	('countryJP', 'Japan'),
	('countryJO', 'Jordan'),
	('countryKZ', 'Kazakhstan'),
	('countryKE', 'Kenya'),
	('countryKI', 'Kiribati'),
	('countryKW', 'Kuwait'),
	('countryKG', 'Kyrgyzstan'),
	('countryLA', 'Laos'),
	('countryLV', 'Latvia'),
	('countryLB', 'Lebanon'),
	('countryLS', 'Lesotho'),
	('countryLR', 'Liberia'),
	('countryLY', 'Libya'),
	('countryLI', 'Liechtenstein'),
	('countryLT', 'Lithuania'),
	('countryLU', 'Luxembourg'),
	('countryMO', 'Macau'),
	('countryMK', 'Macedonia [FYROM]'),
	('countryMG', 'Madagascar'),
	('countryMW', 'Malawi'),
	('countryMY', 'Malaysia'),
	('countryMV', 'Maldives'),
	('countryML', 'Mali'),
	('countryMT', 'Malta'),
	('countryMH', 'Marshall Islands'),
	('countryMQ', 'Martinique'),
	('countryMR', 'Mauritania'),
	('countryMU', 'Mauritius'),
	('countryYT', 'Mayotte'),
	('countryMX', 'Mexico'),
	('countryFM', 'Micronesia'),
	('countryMD', 'Moldova'),
	('countryMC', 'Monaco'),
	('countryMN', 'Mongolia'),
	('countryMS', 'Montserrat'),
	('countryMA', 'Morocco'),
	('countryMZ', 'Mozambique'),
	('countryMM', 'Myanmar [Burma]'),
	('countryNA', 'Namibia'),
	('countryNR', 'Nauru'),
	('countryNP', 'Nepal'),
	('countryNL', 'Netherlands'),
	('countryNC', 'New Caledonia'),
	('countryNZ', 'New Zealand'),
	('countryNI', 'Nicaragua'),
	('countryNE', 'Niger'),
	('countryNG', 'Nigeria'),
	('countryNU', 'Niue'),
	('countryNF', 'Norfolk Island'),
	('countryKP', 'North Korea'),
	('countryMP', 'Northern Mariana Islands'),
	('countryNO', 'Norway'),
	('countryOM', 'Oman'),
	('countryPK', 'Pakistan'),
	('countryPW', 'Palau'),
	('countryPS', 'Palestinian Territories'),
	('countryPA', 'Panama'),
	('countryPG', 'Papua New Guinea'),
	('countryPY', 'Paraguay'),
	('countryPE', 'Peru'),
	('countryPH', 'Philippines'),
	('countryPN', 'Pitcairn Islands'),
	('countryPL', 'Poland'),
	('countryPT', 'Portugal'),
	('countryPR', 'Puerto Rico'),
	('countryQA', 'Qatar'),
	('countryRE', 'Reunion'),
	('countryRO', 'Romania'),
	('countryRU', 'Russia'),
	('countryRW', 'Rwanda'),
	('countrySH', 'Saint Helena'),
	('countryKN', 'Saint Kitts and Nevis'),
	('countryLC', 'Saint Lucia'),
	('countryPM', 'Saint Pierre and Miquelon'),
	('countryVC', 'Saint Vincent and the Grenadines'),
	('countryWS', 'Samoa'),
	('countrySM', 'San Marino'),
	('countryST', 'Sao Tome and Principe'),
	('countrySA', 'Saudi Arabia'),
	('countrySN', 'Senegal'),
	('countryRS', 'Serbia'),
	('countrySC', 'Seychelles'),
	('countrySL', 'Sierra Leone'),
	('countrySG', 'Singapore'),
	('countrySK', 'Slovakia'),
	('countrySI', 'Slovenia'),
	('countrySB', 'Solomon Islands'),
	('countrySO', 'Somalia'),
	('countryZA', 'South Africa'),
	('countryGS', 'South Georgia and the South Sandwich Islands'),
	('countryKR', 'South Korea'),
	('countryES', 'Spain'),
	('countryLK', 'Sri Lanka'),
	('countrySD', 'Sudan'),
	('countrySR', 'Suriname'),
	('countrySJ', 'Svalbard and Jan Mayen'),
	('countrySZ', 'Swaziland'),
	('countrySE', 'Sweden'),
	('countryCH', 'Switzerland'),
	('countrySY', 'Syria'),
	('countryTW', 'Taiwan'),
	('countryTJ', 'Tajikistan'),
	('countryTZ', 'Tanzania'),
	('countryTH', 'Thailand'),
	('countryTG', 'Togo'),
	('countryTK', 'Tokelau'),
	('countryTO', 'Tonga'),
	('countryTT', 'Trinidad and Tobago'),
	('countryTN', 'Tunisia'),
	('countryTR', 'Turkey'),
	('countryTM', 'Turkmenistan'),
	('countryTC', 'Turks and Caicos Islands'),
	('countryTV', 'Tuvalu'),
	('countryUM', 'U.S. Minor Outlying Islands'),
	('countryVI', 'U.S. Virgin Islands'),
	('countryUG', 'Uganda'),
	('countryUA', 'Ukraine'),
	('countryAE', 'United Arab Emirates'),
	('countryGB', 'United Kingdom'),
	('countryUS', 'United States'),
	('countryUY', 'Uruguay'),
	('countryUZ', 'Uzbekistan'),
	('countryVU', 'Vanuatu'),
	('countryVA', 'Vatican City'),
	('countryVE', 'Venezuela'),
	('countryVN', 'Vietnam'),
	('countryWF', 'Wallis and Futuna'),
	('countryEH', 'Western Sahara'),
	('countryYE', 'Yemen'),
	('countryZM', 'Zambia'),
	('countryZW', 'Zimbabwe');